<?php
$z[0]=Array("story_bigimg","",10,62);
$z[0][4]['function']="getListImgSrc(@me)";
$z[1]=Array("story_bigimg","",77,129);
$z[1][4]['function']="getListImgSrc(@me)";
$z[2]=Array("story_bigimg","",230,252);
$z[3]=Array("story_title","",341,361);
$z[4]=Array("story_discribe","",389,477);
$z[4][4]['function']="(strlen(\"@me\")>80?cn_substr(\"@me\",80).\"…\" : \"@me\" )";
$z[5]=Array("story_site","",595,614);
$z[6]=Array("arcurl","",725,740);

?>