<?php
$z[0]=Array("story_bigimg","",10,62);
$z[0][4]['function']="getListImgSrc(@me)";
$z[1]=Array("story_bigimg","",77,124);
$z[1][4]['function']="(@me +++++++)";
$z[2]=Array("story_bigimg","",225,247);
$z[3]=Array("story_title","",336,356);
$z[4]=Array("story_discribe","",384,472);
$z[4][4]['function']="(strlen(\"@me\")>80?cn_substr(\"@me\",80).\"…\" : \"@me\" )";
$z[5]=Array("story_site","",590,609);
$z[6]=Array("arcurl","",720,735);

?>