<?php
$z[0]=Array("id","\r\n				<div class=\"case_item\">\r\n		            <div class=\"case_img\"><img src=\"[field:story_bigimg function='GetOneImgUrl(@me,1)'",0,139);
$z[1]=Array("story_title","",212,232);
$z[2]=Array("story_discribe","",260,348);
$z[2][4]['function']="(strlen(\"@me\")>80?cn_substr(\"@me\",80).\"…\" : \"@me\" )";
$z[3]=Array("story_site","",466,485);
$z[4]=Array("arcurl","",596,611);

?>