<?php
$z[0]=Array("story_bigimg","",10,62);
$z[0][4]['function']="getListImgSrc(@me)";
$z[1]=Array("story_bigimg",")'",77,164);
$z[1][4]['function']="(preg_match(\"/href=\\'(.+\\.\\S+)\\'/\",@me,@arr):@arr[1";
$z[2]=Array("story_bigimg","",265,287);
$z[3]=Array("story_title","",376,396);
$z[4]=Array("story_discribe","",424,512);
$z[4][4]['function']="(strlen(\"@me\")>80?cn_substr(\"@me\",80).\"…\" : \"@me\" )";
$z[5]=Array("story_site","",630,649);
$z[6]=Array("arcurl","",760,775);

?>