<?php
$z[0]=Array("global","",122,154);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel","\r\n            <a href='[field:typeurl/]'>[field:typename/]</a> \r\n            [field:global name=autoindex runphp=\"yes\"](@me!=5)? @me=\"|\":@me=\"\";[/field:global] \r\n            ",315,537);
$z[1][4]['type']="top";
$z[1][4]['row']="6";
$z[2]=Array("global","",580,602);
$z[2][4]['name']="address";
$z[3]=Array("global","",619,645);
$z[3][4]['name']="cfg_powerby";

?>